global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
 
scrape_configs:

  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://70.34.255.158:8080/ui/
        labels:
          app: 'qr-code-app'
          service: 'web-ui'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [app]
        target_label: instance
      - source_labels: [__param_target]
        target_label: target_url

  - job_name: "blackbox-tcp"
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - "70.34.255.158:8080"
        labels:
          app: 'backend-tcp'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [app]
        target_label: instance
      - source_labels: [__param_target]
        target_label: target_url
